// Mocks generated by Mockito 5.4.6 from annotations
// in tapo/test/services/tpap_client_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:tapo/core/tpap_session.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTpapCredentials_0 extends _i1.SmartFake
    implements _i2.TpapCredentials {
  _FakeTpapCredentials_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TpapSession].
///
/// See the documentation for Mockito's code generation for more information.
class MockTpapSession extends _i1.Mock implements _i2.TpapSession {
  MockTpapSession() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get deviceIp =>
      (super.noSuchMethod(
            Invocation.getter(#deviceIp),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#deviceIp),
            ),
          )
          as String);

  @override
  _i2.TpapCredentials get credentials =>
      (super.noSuchMethod(
            Invocation.getter(#credentials),
            returnValue: _FakeTpapCredentials_0(
              this,
              Invocation.getter(#credentials),
            ),
          )
          as _i2.TpapCredentials);

  @override
  bool get isEstablished =>
      (super.noSuchMethod(Invocation.getter(#isEstablished), returnValue: false)
          as bool);

  @override
  _i4.Future<void> probeDevice() =>
      (super.noSuchMethod(
            Invocation.method(#probeDevice, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> testTlsConnection() =>
      (super.noSuchMethod(
            Invocation.method(#testTlsConnection, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> handshake() =>
      (super.noSuchMethod(
            Invocation.method(#handshake, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>?> request(Map<String, dynamic>? payload) =>
      (super.noSuchMethod(
            Invocation.method(#request, [payload]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
